### ISSUE TITLE
ToC starting at the bottom of the page

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#388] opened 2022-08-16 16:58 UTC
Not sure how this occurred but presently, the ToC on my https://retypetest.pages.dev/reference/glossary/ page (in Edge on Windows 11) is starting at the bottom:

![gap](https://user-images.githubusercontent.com/24688509/184936283-f264dfdb-3d60-4b91-987d-521eb2c39846.png)

All other pages are fine; however, if I access another page directly from the Glossary page, the same issue occurs:

![gap2](https://user-images.githubusercontent.com/24688509/184936341-ffa0693d-4f43-4a0d-9656-753a9535a919.png)

If I refresh that page, it's fine. But once I return to Glossary, the issue recurs:

![gap3](https://user-images.githubusercontent.com/24688509/184936374-e0601bcd-dedb-44cc-8e25-6f4afb8ed39a.png)

**Comment by geoffreymcgill** [comment] 2022-08-16 17:03
It looks like there is a JavaScript error being triggered on the page. We will have to investigate and try to figure out why. 

Are you able to share or link me to the `.md` source for that page? Using the original source should help us be able to recreate and isolate the error.

**Comment by xyeLz** [comment] 2022-08-16 19:36
No problem at all. I appreciate the quick response and identification of the issue. I could suggest an alternate feature for panels with no content: having them show anyways but drop down no content; however, I also like being able to "stage" them and not have them appear, so I'm torn on this one. ;) In any case, thank you!

**Comment by geoffreymcgill** [comment] 2022-08-17 19:38
This issue has been fixed and I can confirm your `glossary.md` page now renders correctly.

<img width="1059" alt="Screen Shot 2022-08-17 at 1 36 57 PM" src="https://user-images.githubusercontent.com/62210/185227692-de1d8db4-7434-470b-b5a3-0b1afef85385.png">

The fix will be included in the next public release of Retype.

**Closed by geoffreymcgill** 2022-08-17 19:38 UTC
Labels: bug
