### ISSUE TITLE
BUG: Tables are not rendered (sometimes)

### ISSUE THREAD

**Issue by R-Studio** [retypeapp/retype#304] opened 2022-03-22 07:30 UTC
I love the new v2.0.0 of ReType but I think there is a bug in table rendering that occurs sometimes.

**Markdown Code**
```
| Component                      | What it does                                                           | GitHub repo                                                                                 |
| ------------------------------ | ---------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| Longhorn Backing Image Manager | Backing image download, sync, and deletion in a disk                   | [longhorn/backing-image-manager](https://github.com/longhorn/backing-image-manager)         |
| Longhorn Engine                | Core controller/replica logic                                          | [longhorn/longhorn-engine](https://github.com/longhorn/longhorn-engine)                     |
| Longhorn Instance Manager      | Controller/replica instance lifecycle management                       | [longhorn/longhorn-instance-manager](https://github.com/longhorn/longhorn-instance-manager) |
| Longhorn Manager               | Longhorn orchestration, includes CSI driver for Kubernetes             | [longhorn/longhorn-manager](https://github.com/longhorn/longhorn-manager)                   |
| Longhorn Share Manager         | NFS provisioner that exposes Longhorn volumes as ReadWriteMany volumes | [longhorn/longhorn-share-manager](https://github.com/longhorn/longhorn-share-manager)       |
| Longhorn UI                    | The Longhorn dashboard                                                 | [longhorn/longhorn-ui](https://github.com/longhorn/longhorn-ui)                             |
```

**GitHub rendering (What I want)**
![image](https://user-images.githubusercontent.com/7498854/159429130-a6265b6a-ccf1-416a-ac31-9caa61f39212.png)

**ReType rendering**
![image](https://user-images.githubusercontent.com/7498854/159429527-a5be1c40-0faf-4372-b834-2b75cfd9d54d.png)

**Comment by fabriciomurta** [comment] 2022-03-22 08:43
I see a rendered table similar to what you described at https://r-studio.github.io/obsidiantest/#subsubtitel-of-some-test-text

I have tried to copy-paste it in a local retype repository and it is rendered as a table as well.

**Comment by geoffreymcgill** [comment] 2022-03-23 23:14
I was not able to reproduce this table rendering issue either.

I'm going to close this issue for now, but if anyone discovers what steps are required to reproduce this issue, please let us know and we'll re-open the issue.

**Closed by geoffreymcgill** 2022-03-23 23:14 UTC
Labels: invalid
