### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by slimooo** [retypeapp/retype#29] opened 2021-06-10 22:23 UTC
Hi,

Maybe I found a bug in "order option".  

![bug order](https://raw.githubusercontent.com/slimooo/dpo/main/Capture%20d%E2%80%99%C3%A9cran%202021-06-11%20%C3%A0%2000.09.51.png)

Synthèses -> order: 99
Titre -> order: 90
Clauses à modifier -> order: 50
Clauses à ajouter -> order: 49

**Comment by slimooo** [comment] 2021-06-10 22:50
It's really strange : https://www.loom.com/share/799de2a782fa458e80da695fb9e7b3d8

**Comment by geoffreymcgill** [comment] 2021-06-10 23:25
Thank you for the bug report. We are investigating and I suspect I know what is going wrong. We'll try and figure out if there is a work-around, or maybe a patch release will be required. We're anticipating the release of `v1.7.0` should be relatively quick, so maybe the fix can wait till then.

**Comment by geoffreymcgill** [comment] 2021-06-11 18:20
@slimooo Questions?

1. Are you using Retype `v1.6.0`? You can check with the command `retype --version`
2. Can you post the exact file and folder names you have configured for those pages?
3. Is your project available in a public GitHub repo? Then we could test against the exact same project you are working with which would help ensure we fix the defect.

**Comment by slimooo** [comment] 2021-06-11 18:29
1. 1.6
2. Sorry, I delete the project
3. No sorry

**Comment by geoffreymcgill** [comment] 2021-06-16 21:35
We believe this issue was caused by some lack of functionality in Retype where the `Previous | Next` buttons are only rebuilt on the newly revised page and navigation, but any associated pages remain untouched causing the `Previous | Next` buttons get out of sync.

This issue would likely only be a problem when running Retype locally with the built in server (`retype watch`). 

The work-around is easy, and either of the following two options should work-around the problem:

1. Stop the server with `ctrl + c` and restart with `retype watch`, or
2. Run the command `retype build`

Either of those will rebuilt all the pages and sync up the `Previous | Next` buttons.

This issue will not occur on a live site if you are using the [Retype GitHub Action](https://retype.com/guides/github-actions/) as the Action will completely rebuild (`retype build`) the project before publishing to GitHub Pages.

If you are manually publishing your website, please run `retype build` before publishing.

We have a plan to automatically (re)build these associated pages with a new incremental page dependency graph process. The graph is a high priority feature for us and currently scheduled for Retype `v1.9.0`.

**Comment by geoffreymcgill** [comment] 2021-06-16 22:52
Closing this issue, but we will post an update here once the dependency graph has been released.

**Closed by geoffreymcgill** 2021-06-16 22:52 UTC
Labels: bug

**Comment by geoffreymcgill** [comment] 2021-06-18 20:18
We have made a big update to how Retype handles accent characters, which might also help with the above issue. I still think running `retype build` or stop-start `retype watch` will fix the issue above, but the new accent char enhancements are related too.

The enhancements will be included in the upcoming release of Retype `v1.7.0`, which should happen early next week.

**Comment by AndreyChechel** [comment] 2021-09-29 19:16
Just to follow up, since `v1.9` Retype builds and maintains a page dependency graph in `retype watch` mode. This data helps to identify what pages should be rebuilt once Retype has detected a change. This approach is what helps now to have the `Previous | Next` buttons and many other things always synced with the corresponding pages.
