### ISSUE TITLE
Retype v3.4 has an issue with "expanded" 

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#623] opened 2023-09-09 02:22 UTC
Hello!

I have a website  using Retype v3.3 (web-configs) and another one using Retype 3.4 (@squide). Both websites have every folder configured with `expanded: true`.

With `v3.3` it works as expected:

![retype_3 3](https://github.com/retypeapp/retype/assets/794579/b7e28093-7669-4318-8e75-2a46103f5ca4)

But with `v3.4` they keep closing:

![retype_3 4](https://github.com/retypeapp/retype/assets/794579/d7a66c1b-08f2-412c-a2a2-1b5ae24c6b3b)

Thank you,

Patrick

**Comment by geoffreymcgill** [comment] 2023-09-09 02:27
Confirmed, this is a bug introduced with v3.4.0. We are going to fix immediately and make a v3.4.1 patch release, hopefully late tomorrow.

Sorry about this.

Thanks for reporting.

**Comment by geoffreymcgill** [comment] 2023-09-10 15:06
Retype v3.4.1 has been released and includes a fix for this bug. 

This bug was mistakingly introduced when the related `Tree nav expanded state not saving` bug was fixed in v3.4.0. Resetting of the tree navigation was actually a "feature" we had built very early on in Retype, although because of bug that was not caught until v3.4.0, this "feature" was not actually working. 

Things should be working better now. No changes are required in your project, other than upgrading to the latest Retype release. 

@patricklafrance Thanks again for letting us know about this bug.

**Closed by geoffreymcgill** 2023-09-10 15:06 UTC
Labels: bug
