### ISSUE TITLE
Force both burger menu

### ISSUE THREAD

**Issue by Jazzydad** [retypeapp/retype#629] opened 2023-09-13 10:01 UTC
Hi,
Is it possible to force both right and left menu to be always collapsed by default (with the menu burger available) ?

Then the layout will always be like on the pict attached (when the browser size is small).

It will help the reader having a wide central content available for reading.

Maybe the solution is just to change something in the CSS to trigger this layout even for a big browser size?!

Thanks for your help.

![2023-09-13_10h56_35](https://github.com/retypeapp/retype/assets/69957006/be592c63-7cc7-417d-9662-f972180803ac)

**Comment by geoffreymcgill** [comment] 2023-09-20 02:57
At the moment, it is currently not possible to set the sidebars to be collapsed, although this is a feature we plan to implement in a future release.

Even if the sidebars were collapsible, we would likely still force a max-width for the content. Making the content fill 100% of a wide browser window width tends to make content harder to read.

Closing this issue as a duplicate of #40.

**Closed by geoffreymcgill** 2023-09-20 02:57 UTC
