### ISSUE TITLE
Implement ability to change primary theme color

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#384] opened 2022-08-11 20:12 UTC
I'm guessing this is probably doable by mucking with the CSS but I figured it would be worth suggesting as a feature to have the ability, perhaps per-project, to change the primary theme color of the page from blue to something else. I'm not sure if it would make the most sense for this to be a preset color (such as "purple" or "teal") or if it would be possible to allow the user to input a custom hex/RGB code. Obviously, I'd prefer the latter since it gives the user more flexibility.

**Comment by geoffreymcgill** [comment] 2022-08-11 20:30
This is a big goal of ours for Retype, but it's also a complicated task for us right now. After our next release, I'm going to try my best to make this priority again. 

Closing as this is basically a duplicate of #42.

**Closed by geoffreymcgill** 2022-08-11 20:30 UTC
Labels: duplicate
